# @package _global_

defaults:
  - plugins: null
  - trainer: inference.yaml

  # override config either in this file or using experiment config
  - _self_
  - experiment: null # experiment configs allow for version control of specific hyperparameters


# Trainer
seed: 1
n_gpus: 0

# Data
data_path: src/molbart/bigdata/seq-to-seq_datasets/uspto_260_test.tsv
# data_path: src/molbart/bigdata/seq-to-seq_datasets/uspto_1_test.tsv
dataset_part: test  # Which dataset split to run inference on: full|train|val|test
vocabulary_path: null
data_device: cpu
task: forward_prediction  # ["forward_prediction", "backward_prediction"]
batch_size: 4  # 64
i_chunk: 0
n_chunks: 1

# Output files
output_score_data: outputs/inference_score_uspto_260_output_score_data.csv
output_sampled_smiles: outputs/inference_score_uspto_260_output_sampled_smiles.json

# Model args
model_path: null
model_type: bart            # ["bart", "unified"]
n_beams: 10
n_unique_beams: null
train_mode: eval

datamodule:
  - SynthesisDataModule

callbacks:
  - ScoreCallback

scorers:
  - FractionInvalidScore
  - FractionUniqueScore
  - TanimotoSimilarityScore:
    - statistics: mean
  - TopKAccuracyScore
